In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('houseprice.csv')

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             5000 non-null   int64
 1   income          4750 non-null   float64
 2   experience      4800 non-null   float64
 3   education       4700 non-null   str
 4   city            4850 non-null   str
 5   job_type        4750 non-null   str
 6   credit_score    4650 non-null   float64
 7   loan_amount     4750 non-null   float64
 8   employment      4800 non-null   str
 9   property_value  4700 non-null   float64
 10  rooms           4850 non-null   float64
 11  years_in_city   4800 non-null   float64
 12  house_price     5000 non-null   float64
dtypes: float64(8), int64(1), str(4)
memory usage: 507.9 KB

In [5]:
def missval(df):
    for col in df.columns:
        if df[col].isnull().any():
            if df[col].dtype=='str':
                df[col]=df[col].fillna(df[col].mode()[0])
            else:
                df[col]=df[col].fillna(df[col].mean())
    return df

In [6]:
df=missval(df)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             5000 non-null   int64
 1   income          5000 non-null   float64
 2   experience      5000 non-null   float64
 3   education       5000 non-null   str
 4   city            5000 non-null   str
 5   job_type        5000 non-null   str
 6   credit_score    5000 non-null   float64
 7   loan_amount     5000 non-null   float64
 8   employment      5000 non-null   str
 9   property_value  5000 non-null   float64
 10  rooms           5000 non-null   float64
 11  years_in_city   5000 non-null   float64
 12  house_price     5000 non-null   float64
dtypes: float64(8), int64(1), str(4)
memory usage: 507.9 KB

In [7]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()
def encodla(df):
    for col in df.columns:
        if df[col].dtype=='str':
            if df[col].nunique()<=3:
                dummies=pd.get_dummies(df[col],prefix=col,dtype=float)
                df=pd.concat([df.drop(columns=col),dummies],axis=1)
            else:
                df[col]=encoder.fit_transform(df[col])
    return df

In [8]:
df=encodla(df)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 15 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   age                       5000 non-null   int64
 1   income                    5000 non-null   float64
 2   experience                5000 non-null   float64
 3   education                 5000 non-null   int64
 4   city                      5000 non-null   int64
 5   job_type                  5000 non-null   int64
 6   credit_score              5000 non-null   float64
 7   loan_amount               5000 non-null   float64
 8   property_value            5000 non-null   float64
 9   rooms                     5000 non-null   float64
 10  years_in_city             5000 non-null   float64
 11  house_price               5000 non-null   float64
 12  employment_Full-time      5000 non-null   float64
 13  employment_Part-time      5000 non-null   float64
 14  employment_Self-employed  5000 non-null   float64
dtypes: float64(11), int64(4)
memory usage: 586.1 KB

In [10]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
num_col=df.select_dtypes(include=['float64','int64']).columns.drop('house_price')
df[num_col]=scaler.fit_transform(df[num_col])

In [11]:
df.head()

,age,income,experience,education,city,job_type,credit_score,loan_amount,property_value,rooms,years_in_city,house_price,employment_Full-time,employment_Part-time,employment_Self-employed
0,0.844444,0.079693,0.808511,0.666667,0.00,0.25,0.539386,0.076097,0.377343,0.400000,0.533333,388334.11,0.0,0.0,1.0
1,0.622222,0.308799,0.446809,0.000000,0.75,0.00,0.434049,0.338097,0.284933,0.495835,0.766667,455230.45,1.0,0.0,0.0
2,0.311111,0.281093,0.276596,0.666667,0.00,1.00,0.784939,0.431076,0.537068,0.400000,0.233333,473574.88,1.0,0.0,0.0
3,0.933333,0.588796,0.744681,0.666667,0.75,0.25,0.595057,0.445361,0.510251,0.000000,0.166667,548769.66,1.0,0.0,0.0
4,0.155556,0.206738,0.127660,0.000000,0.25,0.75,0.616309,0.630131,0.000000,0.800000,0.500000,257429.67,1.0,0.0,0.0

In [12]:
from sklearn.model_selection import train_test_split
x=df.drop('house_price',axis=1)
y=df['house_price']

In [13]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [17]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr

LinearRegression()

In [18]:
lr.fit(x_train,y_train)

LinearRegression()

In [19]:
y_pred=lr.predict(x_test)
y_pred

array([444142.68887235, 476870.60787627, 370240.77238126, 479653.78231339,
       476359.26879937, 480050.25798059, 422430.51137356, 396482.06669202,
       392849.41528829, 539789.53887636, 633893.97647995, 493514.07669283,
       477111.85279441, 350201.98110534, 603653.40892281, 425369.22244781,
       519730.17241479, 377848.3788936 , 415992.29499514, 559837.9103574 ,
       408434.1057644 , 426361.88250258, 525968.77080382, 372017.58213506,
       475303.91324882, 511559.87453835, 482735.04587159, 476654.40488835,
       502367.34332931, 465988.95416207, 459609.81494826, 514891.37037528,
       435621.94388828, 473523.77450591, 337069.76183993, 479589.30625038,
       368036.49272066, 455688.26029996, 470742.09270159, 434169.85195606,
       508411.52959027, 523140.36497164, 594597.71222518, 470474.41213548,
       520886.34094469, 450229.9932854 , 469613.23205291, 469671.40853748,
       497569.39262859, 533864.6511161 , 395975.5152113 , 515996.3112567 ,
       376735.048299  , 472418.34979255, 432237.37347771, 565914.01789327,
       346999.07876717, 443919.07649401, 455661.72773369, 537146.78499521,
       514971.63904514, 533712.90580515, 544893.17594358, 479906.07773791,
       623331.66226583, 345501.89386447, 434802.29385586, 381994.10216217,
       610875.54254217, 433431.5087342 , 428222.22120377, 423851.50792966,
       486773.93286985, 525343.58976661, 416824.43115199, 462826.22899709,
       383440.73525934, 412805.17703339, 545292.63238007, 335145.48604795,
       538571.13386045, 373193.56090359, 355506.64131266, 529819.58606471,
       282022.68537028, 475835.73722273, 419482.80867167, 537120.80246587,
       543702.61248201, 419855.66955496, 495579.12447936, 569093.85703496,
       407355.97347349, 548009.90211486, 438212.51286634, 510112.35611532,
       420305.3102982 , 446312.12475394, 394006.82801298, 592774.61422051,
       401631.30461433, 597415.25412574, 447085.08912599, 422330.49946807,
       441906.18996379, 360768.4290375 , 318169.47846599, 455245.26347298,
       529354.51219929, 457654.18465447, 356742.71683709, 488247.2880685 ,
       444886.56454083, 548115.92782523, 380984.51974252, 337359.78555357,
       527768.69098357, 555655.15222296, 500574.85175538, 385066.36219162,
       264430.29478139, 396087.80503815, 493291.24634529, 312413.27779742,
       494393.07181918, 410750.98809606, 451626.69607504, 436226.85896102,
       381529.46131597, 438636.72053518, 550483.31999009, 515891.09360299,
       433506.56360699, 418063.02913985, 472240.62197058, 366040.63153245,
       428534.55606315, 432962.91826197, 403935.72700258, 437474.41765432,
       478769.58099441, 490731.45620086, 472273.57975995, 351403.81236112,
       413962.05209483, 439190.2781289 , 387130.93239599, 567855.78709472,
       419848.2439106 , 405211.96433735, 529842.52564056, 464642.27132655,
       456128.12772486, 441718.77357071, 446981.04577697, 435131.94292414,
       510123.85843498, 509815.13745356, 517027.70762611, 352368.516645  ,
       547842.47228184, 493996.39061846, 508250.03390529, 565542.02297229,
       537847.33058065, 520521.59188311, 435561.19236212, 401468.68882539,
       485370.5873366 , 266407.31416767, 570538.77318992, 385012.06608105,
       649908.41722258, 509118.08869532, 417890.36210862, 472110.90429718,
       283973.8261114 , 431342.50349601, 488047.10644824, 578064.20640554,
       494925.33175767, 543338.70945851, 470351.43068322, 459376.6125829 ,
       475859.63839848, 381630.24351887, 503497.69399463, 525136.9910722 ,
       365196.92247713, 509335.38358882, 480702.68233423, 364614.19133447,
       599471.51525119, 383303.14966744, 478753.09994035, 547412.18660179,
       310382.18364867, 587964.98816323, 434504.77912446, 647392.58832461,
       528707.91466372, 436858.68339071, 484331.76371472, 397158.81482679,
       480826.62760848, 537245.90977877, 515452.84438097, 577600.46264499,
       484606.96238869, 421356.46547909, 512724.01615558, 439669.5789162 ,
       478145.22397076, 420906.19297944, 432376.68912056, 524643.30339599,
       434450.45384489, 482706.60907835, 453146.05806013, 478478.0546237 ,
       510348.30088397, 432750.57641621, 366086.19189273, 523232.92905907,
       578061.80622909, 295743.76451683, 472991.65321171, 499813.0955283 ,
       466141.04952921, 543334.56163617, 464433.24035758, 490181.32696971,
       593199.91772544, 321005.85079976, 537946.08917656, 543834.48031723,
       603199.72366685, 370388.1731752 , 343960.32814714, 412445.26002066,
       371160.40220449, 473280.03005113, 420199.61187861, 509076.94620588,
       339400.54906455, 530428.12881633, 406055.00046977, 421698.65352867,
       501688.42793848, 502153.14298591, 430689.08042137, 367519.93002709,
       560443.28468309, 418154.14974673, 445504.4781285 , 526074.30020501,
       395555.95933253, 668339.64187918, 413090.34966541, 385599.68501075,
       380851.69108283, 481355.48751956, 329492.88444149, 556118.80482372,
       375974.5461876 , 460114.64643002, 417885.22251823, 461639.20835993,
       563644.41447518, 456493.41666335, 471742.93699054, 558064.34576181,
       396950.95159035, 331057.69278313, 531494.67388445, 363531.77690391,
       612821.09925313, 425789.12821213, 501484.93024814, 445415.73877089,
       554403.25620866, 440974.21240874, 482495.535665  , 573384.82072279,
       419428.04618437, 580236.62326848, 428612.35257009, 432291.75514289,
       364145.8899618 , 515745.00925036, 461884.98162122, 456527.72106296,
       461312.34640529, 405766.40655947, 435193.29464216, 546042.15929556,
       387732.00021539, 569062.77298782, 459326.4513492 , 547221.50196025,
       529549.67218861, 547822.01529103, 388780.18288879, 317637.35125697,
       466961.97171102, 575187.15365192, 561451.24187137, 483450.29350041,
       464316.31683159, 492801.79370939, 474568.05113999, 572966.16985142,
       284693.90756523, 446002.83727923, 418427.70384964, 402714.33803802,
       472596.85273093, 338428.18228457, 483036.67039382, 448910.78607469,
       444106.34088744, 445969.01032712, 516305.03345926, 504768.51148194,
       397651.4921132 , 336949.0776247 , 393235.65989561, 494527.04096679,
       510076.58720971, 513537.59497304, 670403.16185982, 526300.22980322,
       458218.40384274, 432231.28358642, 487851.33289359, 323260.65426481,
       340114.87734349, 431263.20909877, 414040.6347047 , 460542.38488088,
       372238.05959788, 409174.71214952, 421123.7468247 , 387623.11939967,
       480731.18366196, 415307.45282679, 412651.10623693, 430358.64825282,
       360165.90253963, 552331.31859581, 568478.63967925, 441495.18365406,
       535594.62413278, 438358.23048782, 326865.99840206, 542418.33573052,
       456939.01092173, 499042.66807053, 431259.15629051, 504710.54608704,
       545087.14339871, 453462.85680955, 620699.78325832, 583596.93923935,
       403613.28887934, 510777.95945888, 558182.57028887, 479214.15885449,
       305473.73595446, 428070.21785919, 417713.98490441, 457494.42585638,
       412429.73557067, 527062.96037836, 435459.24681268, 555184.91788319,
       421756.99596089, 401966.18848301, 467367.27318248, 440456.41056654,
       445678.42529104, 422958.03150898, 556955.59839787, 529554.07693776,
       368130.26654758, 502508.69735847, 350828.56526485, 464486.45594865,
       534680.92980254, 446066.94893064, 527110.24531493, 500125.14940526,
       531000.57540891, 447912.81934888, 282149.36817895, 664143.81165309,
       576101.14281251, 480919.24351431, 456890.24469932, 455410.96374774,
       407450.98836739, 365977.54897065, 467649.95248162, 399129.04547003,
       606911.05304953, 509340.42268539, 557496.57842865, 503065.39685456,
       424767.92386744, 311753.21588255, 380618.12422923, 433549.92915978,
       504084.13490099, 515041.49603166, 487360.75765746, 471616.6294232 ,
       466724.05319041, 467653.50910223, 449514.09475164, 333746.32068744,
       411593.63884804, 478357.29399221, 551334.5088988 , 439376.79967367,
       395597.83594409, 491143.30510172, 476673.60549781, 324046.97595002,
       419434.38649711, 363862.4397045 , 451286.07629011, 457765.21136646,
       484012.62446921, 363707.3552256 , 389547.57886649, 457853.26695735,
       640504.89806376, 396921.37112079, 447002.96319865, 336699.1049531 ,
       433138.52652696, 509425.60776965, 493351.29017632, 417231.12852161,
       429435.70322654, 446568.49012417, 474207.28797155, 544232.59543554,
       553465.64025302, 338337.50497955, 458633.29909203, 483022.06439991,
       412602.93571271, 396236.88651126, 343357.31367998, 505179.52827789,
       478004.92160835, 391465.79421042, 509436.14394324, 419462.95333678,
       383162.38556214, 415830.9271469 , 474289.35124138, 545137.62237168,
       366263.9717145 , 418208.68539587, 585724.71827087, 539943.17603123,
       523829.48956008, 482452.08012864, 545654.16857812, 429539.52015012,
       545480.07065034, 504394.32919814, 464415.95751169, 357136.74877259,
       456001.53779036, 491050.55358035, 295203.35545286, 265647.32494369,
       387998.62428098, 338418.29485251, 547628.94800812, 561182.3509405 ,
       419239.95067989, 454824.63656536, 400885.15043135, 339309.58671315,
       501917.34187431, 548206.41207252, 446047.18495409, 504439.06342066,
       462023.96947953, 492832.09720231, 585238.52171766, 482610.11892645,
       526041.33776837, 546450.98252204, 519694.94311606, 506919.02363666,
       499816.12197935, 352466.34267565, 348418.67760714, 625650.01896634,
       448547.15875295, 447123.33045859, 486645.02203275, 315047.41059203,
       344951.60138123, 447695.57027444, 519399.96099172, 562122.77457489,
       474785.78469785, 507048.04545785, 531573.57437445, 389355.74136837,
       453891.47776514, 351252.68430877, 434942.66553192, 368730.06953978,
       327541.9002723 , 492197.37154024, 386939.38315785, 520244.50274031,
       534122.77438871, 436310.04859139, 358806.37780334, 546876.87319092,
       483340.60906084, 515078.20822587, 543571.94160342, 354513.35638005,
       319803.77148789, 325382.91388883, 398804.43963069, 456380.76991893,
       431644.35094052, 371085.33726528, 455470.9440809 , 461037.21490318,
       521545.96418409, 349116.30637449, 379870.25724654, 431477.48390544,
       414714.38793201, 391112.57919653, 557004.53354236, 385268.98663709,
       422205.84432328, 458788.3859907 , 437376.95381302, 482955.78452715,
       548416.36529496, 546243.79954199, 425961.52933214, 537652.43196899,
       510098.56599413, 397976.64931191, 399181.35628493, 433114.70545158,
       330012.18637585, 564170.9743014 , 414488.84958016, 470516.70345643,
       322966.45148217, 466667.59730347, 411971.14344474, 495914.73713011,
       366653.74190704, 388830.77169335, 394804.66166408, 377207.49950513,
       485141.35762769, 495905.16228338, 372288.71309365, 391137.79143739,
       533221.20240901, 390313.98538755, 509197.66432044, 416095.56400355,
       456455.61887936, 528689.98594531, 550978.17493208, 310108.23989455,
       530321.13728948, 492987.15681668, 427075.55729756, 613341.56915059,
       500482.29033282, 471754.81918042, 391583.25129962, 471066.93835464,
       372370.69795859, 391965.50325722, 507187.90443194, 447771.4433938 ,
       414674.62809031, 379251.39652057, 450840.94646538, 392170.86874285,
       446977.9264542 , 430977.35786584, 520464.19551864, 403417.15589986,
       439366.42370795, 484689.87935283, 430030.36841803, 433250.31472832,
       394536.90982453, 512805.41294968, 619574.05705219, 376467.89105078,
       414896.96195444, 358796.82830086, 472031.56906169, 525950.19292452,
       342943.69702506, 442992.3705343 , 265517.19803963, 487257.15290045,
       481457.23285373, 381406.80383396, 721128.31468274, 436279.70200392,
       311023.20518286, 513933.49428018, 534672.27324099, 475784.57011928,
       525290.20870398, 459206.47167158, 375820.7265282 , 456528.90912386,
       494371.74115386, 538218.4948996 , 450253.89663176, 507738.47846147,
       360606.1693756 , 512313.40720231, 512878.44205   , 495544.37500689,
       478669.19125157, 393741.29157152, 492561.5665406 , 395735.37310161,
       530685.58996451, 415393.83840155, 483970.42693682, 355362.86228074,
       414223.58567908, 521869.44148108, 407197.76996353, 329313.11539373,
       549463.13429162, 584310.36648919, 573218.59428721, 357267.02438204,
       420580.53351041, 467075.44667283, 358002.06945057, 488438.43431361,
       371695.4388197 , 561650.83637758, 418291.09003162, 415936.7203809 ,
       430067.50636846, 394113.74924553, 559997.3210385 , 332842.30084632,
       507378.59687154, 477567.87307026, 336965.43114392, 588944.70377974,
       313260.08055056, 429355.54163994, 565365.94998017, 478458.73022112,
       406885.03263251, 423230.82567946, 368988.33629235, 437396.19471471,
       360197.42044433, 501714.48542335, 428589.28393586, 435594.54630297,
       405149.91322346, 412530.8397358 , 470886.69263457, 408646.62099123,
       507858.32318149, 446821.9148185 , 394711.32581201, 318546.76523373,
       564204.23881486, 499030.43612302, 462604.13686139, 553272.18216564,
       495005.8650158 , 552130.66392701, 450414.39574073, 584962.19353724,
       338465.95912303, 378486.49075294, 363466.77718029, 421774.77005886,
       432162.59049373, 417922.65766486, 430095.54135634, 472791.66707912,
       443144.06357332, 478392.13832664, 443116.65132115, 430400.60772419,
       493142.76511861, 482252.45577446, 429530.04437733, 488383.34754271,
       440281.1684128 , 571290.34466909, 338760.73248163, 456571.74225853,
       425469.02700853, 475036.92940358, 443551.10615774, 422338.38309136,
       591611.67647877, 523629.14818598, 429125.36184572, 393146.4276429 ,
       572713.49872473, 483897.22960969, 453530.82870181, 462118.52561082,
       508197.51072601, 463623.30490253, 440185.09270761, 560280.02923834,
       601632.56820624, 386200.82209768, 385657.06551994, 411499.64555951,
       499395.56682774, 475468.43987055, 457281.05226448, 433563.44265646,
       397555.16335513, 412989.24341539, 446666.97624164, 355538.4344021 ,
       336553.29491923, 302237.04152955, 426411.09751158, 596376.48240747,
       485149.11517998, 392832.57995952, 461014.12704651, 370989.10665356,
       405162.24526344, 474897.14558175, 343451.82599646, 513092.18633971,
       515827.70012471, 377405.59623937, 322378.57009586, 473645.93705597,
       366456.95179888, 463407.3216027 , 426678.74276592, 494174.94652271,
       442049.40192058, 553342.20427773, 566553.90988271, 459161.59524277,
       566827.11253764, 423773.33547356, 406785.03105673, 396896.992146  ,
       396460.01150449, 535790.77230736, 463176.63562086, 342549.41045504,
       493741.87942489, 572342.63563915, 537165.99198698, 402885.44360617,
       477526.49055718, 376020.15453762, 428531.5880406 , 387718.3743793 ,
       384225.39246013, 448460.63052449, 466162.37599801, 401108.08450145,
       395779.32975744, 392794.69063842, 391338.48866663, 433230.51095459,
       536461.80468746, 276845.92954924, 454203.59306069, 370265.23664281,
       507753.89640799, 590162.95776679, 567880.54343291, 538113.46369411,
       341414.83973949, 290968.07655227, 437348.72635608, 438617.85995785,
       475563.28825059, 316512.29625816, 538636.86176295, 477408.12619961,
       510733.4557092 , 442646.60778692, 597402.28560408, 487371.49894275,
       430576.84073477, 508799.13631913, 429616.37075315, 311160.37788777,
       528548.37003718, 482576.33660334, 519955.34450868, 562714.83545208,
       446459.5284125 , 496012.29054231, 487773.09622113, 333298.01260139,
       530981.90741441, 422357.52299256, 487901.73069219, 485916.78647754,
       548960.95395329, 489699.12498563, 461016.09705534, 604087.48779915,
       499246.45686343, 391263.9448166 , 390644.0625847 , 434234.25028845,
       590641.94083224, 443052.489582  , 322179.44090168, 402484.86524844,
       395305.33138261, 456635.19797116, 504450.49812069, 525245.03438091,
       495813.16329891, 475385.56070479, 510922.55010475, 383335.64469502,
       440659.40779788, 271330.5273859 , 474804.32784421, 572298.17875567,
       355946.263066  , 556529.55566398, 376697.30644475, 431623.56473627,
       527239.91111566, 411141.22485726, 382436.65197573, 386107.54276418,
       512676.40300498, 546123.59577901, 445525.71749018, 404169.75124792,
       540091.42011818, 380948.71458859, 568602.51757701, 453775.24953855,
       449707.49694072, 425746.17878795, 471295.67698884, 487606.57517051,
       531272.21002601, 582132.50243298, 384339.08096396, 620341.79639671,
       346723.56660123, 686564.27224108, 448559.46010028, 572340.69258489,
       484509.26653845, 327699.66336681, 485348.76858142, 562859.31762145,
       511906.30291097, 480423.12297403, 523127.1887944 , 403271.44218778,
       388281.60820775, 523320.4765884 , 385280.17917679, 363647.74131508,
       501358.51125035, 315119.34802499, 515655.71048263, 575527.82783666,
       377676.95756557, 481660.50604822, 316480.7292769 , 478120.76520388,
       455216.74041188, 556085.85841303, 408393.272133  , 514457.00395411,
       388874.61555983, 559451.29804686, 362843.31599347, 496806.98164388,
       551723.50318584, 357608.92812897, 369864.04813553, 515514.69121173,
       404218.49733977, 425191.82683494, 478664.06527542, 338084.63820792,
       417526.66990341, 424439.11180097, 370216.19689687, 498867.64286761,
       437879.00845734, 335676.45994023, 351041.64399461, 390253.95081259,
       524308.65023863, 456039.42645295, 401115.17944938, 493365.76467626,
       542423.41929623, 584312.6959488 , 532457.21382744, 347319.40103549,
       462015.66185152, 458392.01791451, 480412.25335114, 387090.17326494,
       303124.10761477, 362560.65738461, 547357.24764174, 491488.36939137,
       520767.18770016, 316679.74280546, 411402.33892159, 588975.7182862 ,
       517801.76225231, 486869.23372996, 368180.55736525, 450813.51523546,
       615965.37388147, 636896.38131313, 480202.56769312, 447478.18086698,
       357722.46663572, 480286.86565583, 488297.76352995, 422102.37376894,
       504725.07694353, 501835.98719047, 411818.22071164, 314793.7821782 ,
       433069.7188985 , 456443.87128133, 370949.0240909 , 486817.03918654,
       497107.99951439, 509874.87747181, 433876.25361758, 506308.90852294,
       422923.3113953 , 411682.10185108, 520832.6345264 , 307203.32684762,
       568763.56233467, 393267.67324607, 471346.1452699 , 476888.44424389,
       508183.22114726, 379745.9143142 , 514465.47995412, 459809.98547564,
       486819.92978643, 452759.98826044, 312043.04955693, 597504.63155573,
       318936.19727421, 414845.54112664, 710165.42713096, 428711.85404354,
       528743.96838394, 244621.37517109, 423653.84064635, 454410.62220126,
       557502.93680478, 542628.01630129, 421568.22005149, 540901.74342996])

In [27]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

In [28]:

print("MAE:", mae),
print("MSE:", mse),
print("R2 Score:", r2)

MAE: 30951.365971969728
MSE: 1548297095.4341044
R2 Score: 0.7870513138596583

In [32]:
from sklearn.model_selection import KFold,cross_val_score
kf=KFold(n_splits=5,shuffle=True,random_state=42)
scores=cross_val_score(lr,x,y,cv=kf,scoring='r2')
print(scores)

[0.78705131 0.76641609 0.75761581 0.76274364 0.75537881]

In [33]:
import numpy as np
np.mean(scores)

np.float64(0.7658411328039728)

In [34]:
from sklearn.tree import DecisionTreeRegressor
dtr=DecisionTreeRegressor()

In [35]:
dtr.fit(x_train,y_train)

DecisionTreeRegressor()

In [37]:
y_pred=dtr.predict(x_test)
y_pred

array([437094.69, 481910.76, 347611.75, 443917.35, 371351.3 , 371174.4 ,
       347611.75, 412380.87, 539739.79, 615980.08, 614392.79, 413814.8 ,
       419844.7 , 352321.65, 611404.25, 452463.24, 531694.74, 404917.65,
       255778.38, 557736.53, 407709.6 , 398881.9 , 574515.05, 349601.72,
       411050.08, 478459.39, 444495.91, 520787.09, 472160.74, 506632.15,
       451967.88, 482931.91, 396320.52, 506643.61, 380438.44, 521580.22,
       346839.08, 434827.47, 475417.92, 426792.99, 580528.13, 578940.9 ,
       555512.94, 505322.35, 546091.06, 465896.05, 455108.72, 441602.08,
       531913.2 , 532748.47, 382229.42, 537105.48, 345169.35, 434827.47,
       463943.49, 555512.94, 283500.3 , 505156.71, 524692.09, 589841.49,
       509120.75, 543173.95, 599193.77, 581047.49, 562331.28, 351633.62,
       460744.46, 260674.35, 630316.18, 366799.31, 417285.37, 484898.19,
       595366.73, 491186.09, 400052.26, 425942.24, 342599.03, 532957.44,
       558374.  , 292927.89, 504121.12, 353560.52, 426794.42, 553249.17,
       313465.97, 486324.29, 445053.08, 550683.79, 485755.48, 464576.23,
       504351.49, 615980.08, 413616.02, 456106.59, 481240.1 , 515983.32,
       379474.25, 455030.67, 407968.95, 612635.02, 387130.94, 568398.97,
       396753.58, 419840.98, 496941.67, 335601.63, 343570.36, 443449.67,
       450304.76, 470724.54, 381268.5 , 514832.06, 516527.59, 561449.06,
       298641.35, 355708.63, 567073.63, 591983.76, 515573.95, 345211.98,
       241931.97, 503022.8 , 457156.78, 274719.2 , 530822.69, 440948.58,
       515102.57, 414940.81, 360110.44, 512264.21, 573720.38, 510214.42,
       501323.67, 494107.94, 431098.59, 458779.87, 460171.6 , 433224.32,
       429019.18, 479381.58, 440615.09, 534474.57, 487134.68, 407500.91,
       391951.68, 526524.32, 413094.55, 516806.07, 445053.08, 441897.42,
       503002.8 , 455579.94, 503132.34, 488153.84, 506643.61, 456205.41,
       538095.38, 566094.84, 534609.03, 370688.37, 542246.54, 510302.68,
       505322.35, 562234.23, 470271.3 , 506530.01, 412636.85, 437570.96,
       545069.  , 241317.98, 598896.57, 439581.55, 565697.47, 503489.17,
       391221.11, 506643.61, 345169.35, 375688.34, 489496.03, 608768.4 ,
       561020.74, 560530.27, 518087.78, 474661.2 , 453019.34, 343335.52,
       509672.45, 560656.58, 332364.64, 528287.17, 534627.65, 458779.87,
       564911.51, 348830.59, 451297.54, 537663.37, 297894.33, 580606.31,
       518862.82, 618733.16, 534550.12, 422797.45, 330423.76, 299129.16,
       440615.09, 449308.87, 579466.51, 526091.79, 446316.5 , 456566.21,
       509638.89, 462917.79, 503747.89, 382283.45, 354004.62, 473144.2 ,
       452335.41, 510074.14, 368602.79, 556304.11, 524685.73, 370550.89,
       393540.98, 529784.62, 591622.27, 206233.55, 420792.7 , 520016.37,
       595366.73, 563386.92, 493514.73, 482425.66, 501572.62, 331112.9 ,
       575397.35, 556922.35, 538334.92, 344148.41, 355708.63, 414377.75,
       405141.88, 436147.66, 438820.33, 569519.61, 367447.48, 605646.45,
       461466.52, 399483.58, 592964.09, 533031.86, 391095.57, 467552.67,
       501572.62, 528662.81, 325382.66, 459413.18, 402485.72, 705857.75,
       458331.46, 379613.32, 356130.66, 478915.81, 345169.35, 591622.27,
       457541.29, 475417.92, 367097.41, 407984.9 , 641434.54, 423242.72,
       431098.59, 577907.21, 414993.18, 380438.44, 565208.51, 280651.71,
       645764.21, 478915.81, 503594.34, 473144.2 , 543805.52, 446861.2 ,
       443917.35, 534379.94, 421761.12, 497265.94, 379345.15, 434829.23,
       361604.05, 486931.86, 460391.82, 376859.34, 461451.49, 403251.12,
       432138.96, 485755.48, 351673.75, 524260.87, 484147.64, 451884.63,
       538668.5 , 573670.64, 332364.64, 375061.76, 437327.98, 570674.26,
       584144.02, 444544.3 , 423822.8 , 437932.98, 520439.3 , 577907.21,
       308895.3 , 378354.34, 401863.15, 370376.43, 385985.33, 228714.08,
       504232.37, 406750.06, 423535.31, 477125.56, 476347.69, 575898.66,
       381268.5 , 334268.11, 361078.74, 374172.72, 524685.73, 409043.39,
       721474.51, 478054.46, 491075.6 , 404917.65, 494184.13, 394515.37,
       374190.61, 446130.1 , 431477.53, 504964.86, 465896.05, 445389.31,
       378354.34, 346999.25, 422825.99, 394947.58, 344533.11, 434507.27,
       368074.5 , 533080.21, 608105.46, 391221.11, 636908.91, 422419.38,
       174009.08, 579979.13, 521176.5 , 530454.46, 401896.13, 505702.33,
       526720.94, 449659.59, 597715.89, 564911.51, 420667.45, 506675.86,
       570573.57, 391816.51, 306153.69, 366799.31, 465896.05, 407315.35,
       419113.9 , 540727.33, 522718.88, 527010.83, 367990.57, 429937.33,
       470457.41, 491347.96, 406383.94, 467614.53, 589841.49, 537660.91,
       322889.65, 556922.35, 406469.78, 522157.58, 527847.76, 419844.7 ,
       553249.17, 499997.86, 547769.55, 459611.  , 309229.21, 618733.16,
       546652.38, 505170.09, 431101.11, 470724.54, 437215.25, 390888.78,
       447956.01, 350602.61, 665616.7 , 494184.13, 560530.27, 459413.18,
       427722.61, 256281.35, 467711.9 , 389537.01, 503776.62, 478984.07,
       527409.63, 595366.73, 461505.16, 593089.75, 434695.81, 283742.34,
       406274.76, 529657.97, 619850.95, 431101.11, 384098.41, 553100.17,
       526998.2 , 281442.4 , 441398.15, 345418.44, 534346.57, 396761.34,
       505170.09, 469478.22, 414066.03, 493999.13, 679012.76, 382847.12,
       493434.8 , 335877.55, 435061.42, 425942.24, 317391.15, 419113.9 ,
       422214.06, 528662.81, 531517.43, 543442.5 , 599087.16, 356768.66,
       478683.51, 470764.59, 415179.52, 407968.95, 287585.7 , 626716.77,
       478136.35, 471128.59, 449999.64, 384093.9 , 441776.61, 376669.95,
       483844.29, 475688.01, 376740.44, 429193.01, 651838.11, 535855.64,
       526570.58, 514651.11, 547512.66, 388995.62, 493464.44, 626716.77,
       475209.86, 412008.31, 436233.78, 467749.19, 265560.2 , 279020.96,
       413094.55, 241931.97, 602527.46, 595414.87, 472567.07, 468462.49,
       382769.94, 323029.65, 454978.89, 516943.19, 446627.01, 484720.3 ,
       483815.63, 423996.54, 588177.19, 379379.64, 489299.81, 539662.9 ,
       470213.8 , 520775.95, 488153.84, 360506.05, 362063.01, 639428.85,
       440998.44, 402068.64, 505696.24, 346917.52, 361274.23, 378694.21,
       483624.59, 618630.86, 528262.42, 465548.25, 472685.19, 404473.57,
       443930.89, 332422.64, 613273.98, 311778.98, 384612.91, 494249.15,
       399248.25, 492614.58, 540727.33, 504945.03, 377646.46, 496343.51,
       476025.7 , 557059.81, 538838.35, 472759.26, 385414.86, 370459.5 ,
       454357.98, 432165.99, 418238.46, 415818.07, 453710.28, 477791.9 ,
       522228.47, 362119.64, 370688.37, 501537.57, 484460.98, 394947.58,
       599193.77, 394419.4 , 484147.64, 431167.34, 507648.1 , 432218.95,
       630316.18, 605646.45, 435885.59, 558249.31, 508889.08, 396283.71,
       334665.5 , 456566.21, 264252.21, 508188.84, 420697.01, 473250.64,
       343570.36, 496162.45, 378441.77, 492488.89, 373781.67, 381268.5 ,
       395140.98, 351357.83, 482694.52, 526524.32, 334941.79, 339827.75,
       604384.51, 425208.9 , 470225.85, 457057.88, 454076.94, 537105.48,
       641434.54, 295090.79, 476793.17, 544151.  , 399693.28, 624325.6 ,
       438413.36, 525818.19, 379474.25, 502585.17, 339657.57, 368636.86,
       493514.73, 501323.67, 381537.08, 329255.31, 552738.61, 384024.16,
       496162.45, 404803.79, 493514.73, 431101.11, 468810.37, 547685.56,
       445229.3 , 411042.03, 344533.11, 578940.9 , 662513.19, 399023.71,
       454102.86, 343356.22, 385079.29, 487454.53, 413687.34, 494534.38,
       272590.86, 533509.01, 444214.75, 384517.  , 680128.6 , 473121.38,
       349634.21, 423822.8 , 530321.75, 448720.04, 538668.5 , 605437.43,
       343000.77, 325382.66, 537105.48, 573670.64, 436361.15, 499313.61,
       350786.62, 482250.61, 492424.19, 551869.36, 437327.98, 359049.  ,
       473335.15, 415334.  , 527847.76, 406392.87, 396753.58, 311778.98,
       398711.68, 552039.31, 379173.98, 375661.6 , 578774.48, 548838.33,
       618733.16, 399982.98, 379022.52, 452335.41, 349634.21, 535511.2 ,
       414940.81, 578332.38, 359627.5 , 415998.03, 404424.68, 372749.44,
       549197.01, 400573.1 , 528287.17, 531974.38, 336234.47, 553225.24,
       291180.67, 398017.29, 501572.62, 521514.71, 399899.88, 414604.13,
       334816.87, 465896.05, 407160.82, 549691.85, 449611.72, 444483.97,
       463360.47, 393272.07, 503022.8 , 453191.57, 446861.93, 391221.11,
       336234.47, 343570.36, 601685.  , 460768.16, 495427.36, 516943.19,
       492424.19, 573670.64, 468810.37, 510985.84, 295102.78, 417914.65,
       384612.91, 375688.05, 429019.18, 370653.11, 415179.52, 463390.83,
       441466.58, 487376.28, 436479.41, 450670.72, 505322.35, 433918.88,
       453191.27, 486127.64, 470620.1 , 582631.63, 323912.48, 449842.27,
       377687.34, 457388.8 , 459205.74, 388763.39, 560989.57, 553748.6 ,
       425946.55, 471123.81, 633037.36, 449999.64, 499064.31, 439082.99,
       536634.6 , 463360.47, 442308.05, 485755.48, 627443.12, 371006.01,
       454503.34, 474639.57, 507040.06, 480213.35, 485245.26, 449863.37,
       346887.9 , 364114.78, 359493.  , 322403.83, 351633.62, 228966.93,
       369188.08, 588607.57, 556922.35, 386198.  , 473250.64, 311778.98,
       343000.77, 507613.88, 423551.96, 524349.51, 486931.86, 351357.83,
       283742.34, 418857.38, 380977.69, 531974.38, 502181.79, 442620.85,
       466885.99, 592964.09, 542245.01, 461235.8 , 536634.6 , 265832.99,
       394419.4 , 484254.2 , 431109.15, 509520.73, 580528.13, 344597.54,
       504794.79, 552284.77, 552153.3 , 365261.43, 496940.48, 313236.37,
       488644.69, 409179.27, 339827.75, 443720.01, 492929.41, 516622.56,
       491347.96, 351334.47, 357751.89, 516214.33, 597430.84, 294588.78,
       438577.33, 390457.69, 556922.35, 660311.44, 588177.19, 588177.19,
       448933.64, 308895.3 , 379274.45, 491075.6 , 510678.7 , 256281.35,
       622560.61, 528262.42, 526570.58, 447967.38, 576932.31, 548769.66,
       432699.94, 498599.3 , 527525.85, 335877.55, 455223.19, 366531.4 ,
       524373.78, 599087.16, 537754.97, 520854.35, 434827.47, 390983.71,
       454651.34, 425693.23, 503503.55, 528262.42, 582628.59, 469851.76,
       386955.91, 568303.84, 522157.58, 427770.91, 448475.81, 400419.87,
       578332.38, 415179.52, 308140.12, 443534.67, 358059.8 , 424822.88,
       501572.62, 608293.09, 419521.4 , 478951.38, 539956.21, 368598.6 ,
       431098.59, 306888.61, 455154.71, 633037.36, 382847.12, 590420.42,
       356230.19, 430374.95, 565313.49, 391439.6 , 414390.41, 458331.46,
       594513.98, 539894.74, 593089.75, 407471.99, 475434.82, 373044.76,
       597377.01, 507043.7 , 430374.95, 404560.29, 483844.29, 465043.14,
       613061.8 , 548838.33, 373939.09, 665472.45, 349634.21, 674736.04,
       406890.44, 515332.98, 541372.08, 427854.3 , 480711.28, 487339.87,
       485632.29, 413895.02, 505370.93, 454228.01, 375712.33, 665872.36,
       426187.29, 297894.33, 474727.85, 307396.55, 525784.48, 529382.81,
       365275.92, 503489.17, 286069.24, 503747.89, 526634.44, 502255.67,
       347917.59, 447466.12, 434776.13, 578833.23, 323029.65, 510570.96,
       499400.67, 316207.65, 357751.89, 520405.43, 379861.64, 431098.59,
       484345.53, 237157.48, 403267.3 , 460973.21, 329255.31, 560126.3 ,
       374176.06, 273699.32, 348157.8 , 398230.8 , 526714.59, 501674.6 ,
       339721.95, 479474.28, 516943.19, 597430.84, 549197.01, 367149.71,
       440615.09, 449863.37, 450304.76, 346343.11, 174009.08, 343356.22,
       588177.19, 553948.54, 525518.58, 370459.5 , 338097.22, 507666.09,
       518739.71, 564560.58, 342402.76, 400998.25, 581184.5 , 655013.37,
       484898.19, 452099.26, 376615.48, 474661.2 , 556304.11, 419504.86,
       545252.3 , 528677.77, 369188.08, 298966.61, 408426.08, 451791.84,
       434829.23, 474639.16, 436883.99, 505131.6 , 449954.93, 521840.08,
       400052.26, 454594.58, 627059.32, 333626.99, 607095.24, 395105.87,
       488880.04, 486931.86, 494941.66, 370376.43, 525518.58, 474661.2 ,
       529044.75, 436883.99, 343373.16, 541410.92, 281933.1 , 374078.58,
       673663.13, 365393.16, 547769.55, 272985.64, 441956.25, 493969.71,
       545491.1 , 559965.9 , 484901.97, 502318.35])

In [43]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

In [44]:
print("MAE:", mae),
print("MSE:", mse),
print("R2 Score:", r2)

MAE: 46946.16246
MSE: 3536646999.221373
R2 Score: 0.5135789287163806

In [45]:
from sklearn.model_selection import KFold,cross_val_score
kf=KFold(n_splits=5,shuffle=True,random_state=42)
scores=cross_val_score(dtr,x,y,cv=kf,scoring='r2')

In [46]:
print(scores)

[0.52131867 0.5235462  0.48257083 0.43400682 0.48063838]

In [47]:
np.mean(scores)

np.float64(0.48841617752665617)

In [48]:
from sklearn.ensemble import RandomForestRegressor
rfr=RandomForestRegressor()
rfr

RandomForestRegressor()

In [49]:
rfr.fit(x_train,y_train)

RandomForestRegressor()

In [51]:
y_pred=rfr.predict(x_test)
y_pred

array([448595.6001, 450649.0961, 395246.1009, 489120.853 , 519598.9061,
       468085.8129, 406963.8418, 395666.3544, 414315.2928, 557126.6339,
       595326.8303, 482930.7128, 444270.9686, 349638.3086, 612226.62  ,
       426789.9665, 516895.5974, 384393.1195, 383597.5566, 554207.3476,
       403430.6477, 421497.3818, 543229.3525, 375428.5931, 487558.4883,
       509693.5135, 471383.9401, 470859.5604, 516660.6079, 495546.5698,
       472451.6771, 493202.1599, 443843.4083, 463026.4647, 331899.5905,
       493796.8742, 369413.783 , 450865.0725, 444256.6406, 449089.8706,
       502030.5215, 514299.0281, 592152.8581, 443101.3664, 526789.2092,
       468249.0952, 482475.7779, 454850.0708, 502650.1745, 545147.7963,
       396791.3384, 510187.9438, 381140.0656, 464796.4703, 420067.3693,
       571219.8336, 361230.1611, 477977.4028, 455951.8642, 545717.8274,
       505507.527 , 522711.5764, 521468.6167, 455686.8171, 615262.0936,
       350473.452 , 459163.8568, 359561.2795, 596227.1669, 421500.0171,
       454280.3678, 438902.36  , 470099.5264, 515134.6586, 391459.4766,
       446373.6263, 358174.5608, 400988.5477, 552700.9814, 315957.4168,
       502273.6097, 372627.8436, 341496.6905, 542323.2334, 336027.2047,
       469075.0752, 433545.9152, 522094.5276, 547686.2212, 413497.6632,
       504432.2765, 556547.75  , 411980.4076, 531023.0847, 421312.1371,
       497015.0739, 422602.1702, 435263.8734, 388928.8717, 600991.0118,
       428364.3884, 591901.0108, 418527.5936, 433287.9057, 455495.0413,
       372081.182 , 327659.3197, 462881.989 , 515446.6271, 467250.9706,
       364566.0086, 484921.9211, 475130.1321, 552018.6634, 344010.2914,
       349244.7601, 527984.4895, 566596.939 , 493421.4719, 378782.3046,
       278156.0148, 420314.111 , 520117.2293, 298034.144 , 494646.6863,
       418609.5996, 465254.5047, 415681.4152, 388346.2216, 451467.2354,
       536125.8458, 506781.4511, 447867.9856, 443244.3734, 429171.6406,
       343225.3893, 428696.1468, 431887.6706, 421095.0504, 455570.3911,
       465212.6234, 484102.9526, 493337.5194, 393144.5963, 408547.8551,
       413720.1664, 396630.9543, 591527.1647, 416016.3379, 411663.6291,
       520407.9232, 448559.1988, 479110.9587, 442200.8466, 435951.051 ,
       448423.812 , 510467.6159, 525405.5697, 512700.6588, 361677.987 ,
       514437.7202, 495078.6549, 469235.6513, 550874.227 , 534120.1949,
       522028.8239, 440225.439 , 422251.7653, 474333.363 , 247556.9412,
       567683.3996, 392135.3391, 632687.0515, 524211.3099, 451276.1412,
       446992.6808, 301587.2004, 437952.4731, 465354.903 , 566127.2875,
       495760.9516, 514790.9924, 476840.5703, 456320.3018, 485411.2128,
       401205.8619, 495568.6168, 532526.1995, 352537.806 , 514006.4695,
       519418.5269, 349805.7708, 571354.5405, 369088.2374, 471167.7337,
       567623.7278, 303809.8498, 580210.862 , 439288.8853, 605378.1189,
       526750.3957, 409015.8825, 493362.1492, 388618.0864, 472122.5126,
       516910.727 , 514558.6756, 561520.3348, 483312.6242, 448219.0488,
       509912.8778, 428086.8199, 464717.6814, 365141.0808, 403482.9519,
       518276.7306, 412897.463 , 482876.5138, 392579.9729, 475059.818 ,
       516847.3649, 420364.0822, 348043.8687, 528743.6671, 571762.6971,
       283477.576 , 453962.5535, 468793.682 , 494140.5277, 520974.8321,
       481126.4881, 486868.8911, 568768.8194, 327789.5774, 553343.2275,
       530174.0484, 583759.4773, 380155.3041, 355278.305 , 424820.2282,
       395204.3115, 455450.3722, 431506.8238, 520494.0123, 354602.597 ,
       551604.4469, 422026.6444, 432789.6905, 505396.4674, 474801.2225,
       435484.4265, 387949.1929, 544557.2012, 452114.4692, 423421.4381,
       524239.4034, 423734.0555, 670583.7107, 402735.7563, 402907.0593,
       370360.923 , 467694.8064, 337585.7847, 540646.546 , 367352.8481,
       451653.3257, 431400.6162, 433340.6881, 570355.0017, 444678.0945,
       411241.9745, 554833.6126, 421975.6854, 345298.9514, 540431.2604,
       363045.4158, 601935.8398, 440142.7197, 497136.9012, 448896.5689,
       564127.728 , 441801.9952, 483046.4868, 546162.3491, 435921.1884,
       539240.9343, 439075.3044, 432416.7344, 355113.7106, 502353.3964,
       472380.5405, 425575.2552, 490471.4963, 408253.0075, 418494.6331,
       547718.0712, 376313.275 , 563068.5594, 453487.4358, 506268.4397,
       517053.5905, 548323.1869, 374857.8984, 346525.2854, 467721.3718,
       564635.8616, 561490.5559, 476991.6772, 446695.0132, 476403.2417,
       493484.3474, 561610.9575, 278071.5836, 433658.2352, 434689.4233,
       411283.795 , 449789.969 , 334515.5989, 464218.2237, 432694.3332,
       450654.8048, 467142.4273, 512207.2496, 499795.3907, 377764.1343,
       328509.4646, 399740.0618, 463821.6338, 516762.3629, 490385.4364,
       665769.7181, 523938.1039, 477973.1094, 421167.7726, 501486.5686,
       358724.1229, 358177.4092, 426197.321 , 424034.8098, 476934.7517,
       390603.0666, 428580.9328, 423413.6914, 385262.3539, 463775.3033,
       413490.1376, 403695.4561, 434388.4865, 373811.9278, 545431.6002,
       574954.3511, 458090.1642, 517364.0543, 444637.2544, 325972.0254,
       552157.0051, 482141.0499, 500360.742 , 458292.9002, 506785.1667,
       526906.2214, 452823.1479, 615037.2079, 589939.8967, 421286.2326,
       521882.0711, 559226.0721, 466207.898 , 304737.925 , 421528.1891,
       449381.8594, 445062.9498, 399353.8592, 515264.5498, 469980.6645,
       537915.176 , 390644.035 , 416359.9476, 472974.7068, 440265.8739,
       440708.3073, 452454.5144, 563103.0174, 518720.9337, 346084.2856,
       510177.5376, 372901.7744, 440318.2581, 533488.9588, 442790.8651,
       539764.6936, 487703.7472, 511535.9973, 438958.1312, 274068.3444,
       624345.9218, 548366.8139, 467795.5966, 448034.8406, 456591.0459,
       418315.6706, 367424.1012, 468467.1538, 409250.1921, 610848.0729,
       517526.0119, 534887.9692, 491146.6778, 435739.9422, 307908.934 ,
       391039.328 , 430082.2909, 499340.6805, 514936.4772, 481438.5999,
       496481.1726, 437964.6546, 484915.3372, 435277.2768, 329486.7984,
       408311.9548, 485751.9595, 562819.105 , 432869.8135, 396643.7121,
       502001.9799, 456407.5558, 320189.2718, 426016.6532, 356177.8214,
       496482.0898, 451805.3769, 459141.009 , 387364.142 , 403551.2573,
       468601.2238, 653986.829 , 383711.6999, 442074.6   , 345910.1185,
       437972.4181, 502834.9175, 482151.548 , 396485.0965, 416403.2469,
       459959.8693, 449434.8833, 541849.8599, 548751.8952, 349427.3987,
       477131.8402, 496515.9246, 416892.4169, 388885.6047, 330392.4974,
       516343.992 , 487845.2204, 412788.5224, 495456.5963, 434369.251 ,
       378914.1095, 433635.0748, 479618.7278, 543357.8454, 356445.7164,
       422375.8317, 599964.5265, 554116.6615, 517758.4373, 477835.998 ,
       543260.8589, 429966.1896, 516913.8896, 511399.9675, 456063.0929,
       372583.2393, 453874.2843, 522508.6329, 272352.6365, 295355.2371,
       406340.0442, 351971.2459, 519409.4729, 564146.9478, 406159.8145,
       445109.6137, 374691.6277, 335235.8398, 474437.3308, 541315.4356,
       409816.2177, 502999.5174, 461133.4229, 494164.4942, 571060.8347,
       434057.0996, 513720.595 , 549621.6336, 499923.9178, 504652.8834,
       476836.801 , 337652.8624, 357290.9953, 616071.2354, 436677.2783,
       440261.2245, 505353.2492, 304276.8749, 351949.6585, 422488.3394,
       512782.1857, 545880.0156, 444486.6311, 471993.9609, 503602.1443,
       381714.3138, 453844.6619, 340453.9607, 447249.8397, 350212.6807,
       360393.3827, 466418.1267, 392712.0214, 490256.9249, 529419.7444,
       473291.7256, 361704.9238, 554876.7386, 484873.0451, 529112.416 ,
       532412.1856, 346087.8197, 343628.8788, 337243.8872, 412842.4088,
       450664.4274, 434520.1053, 369453.7618, 439167.9395, 459106.4218,
       531389.0267, 388421.5173, 379425.2065, 452183.8598, 442157.7865,
       381929.1243, 554735.2164, 419909.7922, 436934.4039, 475585.0812,
       431924.61  , 480467.1512, 556517.3546, 565840.2252, 425319.3414,
       546082.0838, 508243.9344, 419418.519 , 397373.8768, 413775.6154,
       338784.1176, 571354.4468, 424286.4353, 453419.7496, 317065.0204,
       464162.5139, 396806.8881, 485600.7778, 362333.6341, 375910.4695,
       407050.1268, 375620.4608, 506282.4128, 470881.8913, 368878.036 ,
       385442.5694, 530311.0282, 387578.6161, 511906.3915, 419265.9315,
       428680.9489, 519570.5751, 598861.4138, 303400.5859, 520204.8548,
       497937.7971, 414851.0304, 590579.4404, 497673.6797, 488453.6512,
       401417.1739, 477308.2987, 355560.8028, 401001.3104, 511053.6556,
       429574.7512, 425271.5728, 369498.383 , 448849.3659, 407635.5583,
       449310.0496, 398972.4855, 518460.5537, 417802.74  , 437269.5056,
       511571.2403, 424302.1431, 405632.152 , 383701.7554, 510331.591 ,
       613809.3007, 378792.2231, 422610.7661, 366385.4138, 456490.9748,
       495460.6002, 395824.2296, 455434.3182, 285148.0269, 519912.9897,
       482562.2756, 395888.9235, 655806.3381, 460467.85  , 298937.1271,
       515113.7494, 519727.9221, 471812.9216, 505199.7698, 483064.5667,
       409433.5353, 444965.0738, 473934.5731, 552672.6918, 456300.072 ,
       503457.0446, 376746.2046, 517914.9412, 516785.7331, 502901.0697,
       463954.5812, 403433.6655, 472051.1884, 415515.2672, 531552.3631,
       410071.746 , 423469.0338, 353277.9734, 426181.1701, 520617.0753,
       419948.0617, 354721.8911, 532917.1495, 568132.8014, 606059.361 ,
       360900.2933, 398645.3533, 452748.6046, 329278.4177, 513276.7797,
       358640.7743, 560511.3385, 405963.7993, 427476.941 , 448769.7815,
       388771.7931, 557715.3681, 358570.0137, 516998.5493, 479800.5508,
       375281.1205, 558522.8191, 335202.9993, 417797.3529, 542535.5599,
       499563.8382, 409883.7966, 432914.7325, 366906.5699, 442445.6592,
       385016.5888, 468146.0326, 417293.9413, 438271.8239, 422141.3576,
       434313.0897, 468940.2869, 412493.6181, 514655.3177, 466375.9048,
       368828.1403, 331367.7179, 582920.6132, 497426.99  , 491081.1153,
       544580.1913, 505705.9255, 543563.6946, 434662.7667, 553065.1559,
       325225.3549, 392519.9653, 365048.3296, 427531.3982, 427324.2721,
       415458.8661, 439258.7997, 474707.5002, 448127.1859, 485259.729 ,
       454936.4286, 434360.0223, 471812.6401, 472611.2169, 416393.5668,
       491686.1066, 442666.2442, 569702.3724, 361287.4728, 477809.6695,
       425858.9652, 464699.2029, 463532.8617, 414874.5793, 584922.8601,
       529336.8433, 418449.5239, 436840.1767, 558085.9066, 465336.1937,
       452956.1241, 437645.2697, 525141.8559, 461929.1542, 450945.6575,
       550787.3695, 588748.3042, 375453.2776, 392036.8916, 427669.5301,
       511800.2022, 506344.6148, 452954.1856, 445655.9041, 408634.9521,
       416500.3958, 455797.2836, 333242.7053, 348397.4661, 304419.4357,
       425722.2204, 584073.6553, 506624.1268, 386467.1394, 468579.0405,
       350545.0788, 411519.578 , 474530.918 , 392950.0351, 511476.0126,
       485512.9285, 378025.0834, 323832.1851, 468819.5925, 374825.15  ,
       459214.3679, 434364.9787, 469317.0159, 446139.7723, 536990.652 ,
       556334.2375, 491094.8   , 557217.7683, 406348.0503, 399516.6989,
       410615.6982, 368063.6632, 521065.3766, 482967.229 , 381651.1644,
       475502.7579, 556641.5852, 521823.9754, 396893.4536, 501738.0364,
       374411.5214, 453169.9992, 398863.642 , 372993.763 , 451009.0256,
       483870.83  , 430260.2558, 436209.651 , 395770.8787, 365592.8078,
       456052.8626, 556685.4378, 307300.6836, 442768.9949, 380111.975 ,
       515920.3715, 579721.0311, 567596.444 , 558576.0077, 345768.07  ,
       280491.1673, 422124.8868, 457391.2958, 472217.9874, 299641.211 ,
       533671.0998, 461804.9011, 537915.8374, 447573.5677, 600417.5655,
       503094.8271, 440686.4067, 492347.7463, 458860.6429, 335896.9876,
       512849.4559, 451062.0981, 524471.1906, 555049.651 , 481323.113 ,
       491632.4076, 481817.794 , 332472.272 , 519521.3037, 422188.6178,
       503072.8953, 459715.995 , 555634.9203, 475896.1381, 451517.5607,
       573990.9873, 491915.6346, 399653.6742, 419094.8755, 423261.0421,
       567751.1208, 446771.9539, 312515.7499, 417291.6128, 403945.6936,
       466989.1644, 492186.9617, 546782.0696, 492364.2817, 480897.7274,
       508294.9434, 405820.3976, 440944.8643, 300501.8831, 478454.2985,
       582621.2291, 362015.2075, 559931.9675, 352496.0592, 432633.9377,
       538030.2   , 410914.2222, 391247.7328, 387128.4692, 525491.4894,
       545444.9127, 481644.3761, 396247.5724, 534663.4413, 380207.2293,
       550926.5962, 470010.2224, 434404.9906, 429776.8691, 486090.0376,
       495585.4656, 527988.1481, 562707.1743, 399499.4433, 600560.2502,
       339577.8711, 672649.4502, 442127.7174, 562592.4855, 481371.5285,
       342162.2557, 483080.967 , 536948.4335, 489238.1565, 446670.7331,
       508273.898 , 414704.8801, 355917.3575, 540800.1537, 390811.3238,
       366784.0545, 504985.9138, 311365.2704, 492021.3834, 572648.1178,
       380507.3099, 506997.8043, 336977.9863, 462961.0263, 488323.4672,
       513401.8751, 415096.337 , 508426.9213, 404132.4613, 550198.791 ,
       340484.6389, 503047.819 , 545384.3428, 359196.5666, 374943.2514,
       515910.5966, 377483.924 , 421341.2959, 497195.8661, 344005.4132,
       424796.1968, 444465.6921, 362619.6898, 519113.6685, 440167.6054,
       320969.6492, 333661.1133, 388067.7044, 513911.112 , 465934.6465,
       391378.6842, 495659.5505, 540827.5369, 561295.388 , 538456.2044,
       358634.0557, 481728.1565, 455593.9384, 491306.7722, 373646.5391,
       292333.2656, 384248.3109, 560074.5386, 529055.3035, 509991.2875,
       317803.2762, 397969.1308, 577023.9795, 520520.0329, 485955.8518,
       368849.9221, 429265.6963, 605158.154 , 664847.6686, 473723.6469,
       463323.9091, 357899.0807, 453888.9447, 461423.2508, 425759.0278,
       509493.7293, 505019.1433, 406281.8199, 312933.9366, 417225.2058,
       463005.6778, 392502.7444, 470056.1405, 505052.2878, 483513.9784,
       436818.4567, 505068.4876, 420294.2991, 439433.3298, 517560.2691,
       306930.4385, 575634.408 , 391585.231 , 462597.7257, 483368.4802,
       515110.1224, 418325.0528, 516918.5627, 458599.9496, 484534.5993,
       481243.7045, 310910.299 , 592269.7868, 308116.8999, 420512.5966,
       652982.634 , 413102.278 , 518468.5451, 270092.0956, 418062.432 ,
       449176.6866, 559099.1077, 559658.0478, 430785.0246, 569475.1513])

In [52]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

In [53]:
print("MAE:", mae),
print("MSE:", mse),
print("R2 Score:", r2)

MAE: 32445.507579000005
MSE: 1675523855.3766196
R2 Score: 0.769552881903965

In [54]:
from sklearn.model_selection import KFold,cross_val_score
kf=KFold(n_splits=5,shuffle=True,random_state=42)
scores=cross_val_score(rfr,x,y,cv=kf,scoring='r2')

In [55]:
print(scores)

[0.77323619 0.75606228 0.74397435 0.74106368 0.73842044]

In [56]:
np.mean(scores)

np.float64(0.7505513903175421)

In [57]:
from sklearn.svm import SVR
svr=SVR(kernel='linear',C=1.0)

In [58]:
svr.fit(x_train,y_train)

SVR(kernel='linear')

In [59]:
y_pred=svr.predict(x_test)
y_pred

array([455147.54292947, 455065.88182004, 454721.4953944 , 455064.46809922,
       455167.22146647, 455356.60416855, 454908.30766814, 454921.95050725,
       454738.21736572, 455253.50700685, 455084.12921038, 454946.26611409,
       454912.29592183, 454788.68719071, 455422.91302383, 454998.36499926,
       455180.23634614, 454710.39738618, 454959.23832094, 455375.69628666,
       455042.97488223, 455082.9396495 , 455219.83228483, 454643.15080409,
       454953.85360686, 455345.12597971, 455292.29488999, 455378.16767864,
       455217.45005403, 454925.37569766, 454939.47264645, 455103.38357956,
       455008.75765341, 455152.39314343, 454790.19254862, 455010.26359064,
       454780.26541539, 455045.55599497, 455030.69708758, 454980.45854917,
       455188.89299924, 455300.38887463, 455385.68190628, 455176.71789404,
       455312.21314894, 455008.07998546, 455174.5397648 , 455194.90834309,
       455127.81854547, 455229.44770756, 454857.96372543, 455225.5761653 ,
       454865.0036232 , 455164.84572121, 455055.19353763, 455182.71584333,
       454864.01018516, 454963.54332475, 455008.52881404, 455259.23979607,
       454998.38789633, 455131.07375466, 455069.4674381 , 455255.10741212,
       455418.42202808, 454704.6453152 , 454960.07552267, 454710.26936764,
       455519.52907951, 455040.81842056, 455058.99329601, 455047.36726464,
       455081.87474555, 455304.29219905, 455037.4984701 , 455064.06808396,
       455092.49963578, 454871.03138078, 455345.63388387, 454891.95689869,
       455494.86759441, 454920.53220627, 454886.46946517, 455299.52905196,
       454747.42543786, 455249.6757498 , 455027.86769781, 455253.14920859,
       455343.00298593, 455031.97435705, 455315.05039351, 455327.63467477,
       454863.76341956, 455461.44878684, 455149.94427294, 455053.95323487,
       455042.63904332, 455063.63526651, 454937.70175366, 455478.7767203 ,
       454912.28041363, 455450.7664683 , 455057.9095206 , 455100.58453322,
       454869.40638349, 454673.3575009 , 454749.98460636, 454964.39562873,
       455430.81432493, 454979.26326259, 454892.05266121, 454942.20058609,
       454953.69447541, 455585.30384549, 455065.19339047, 454707.02095247,
       455091.47305204, 455223.54918756, 455064.69524443, 454672.35150976,
       454547.64372337, 454990.60027079, 455042.98045686, 454735.81298922,
       455279.24818574, 454872.43304921, 455068.99967969, 455209.84779372,
       454920.66946994, 455136.08540493, 455301.93114173, 455098.79446053,
       454763.01865145, 455181.06831283, 455187.51366993, 454917.27875583,
       455181.19706182, 455013.78694441, 454801.11323002, 455249.52725347,
       455059.0415702 , 455032.80962717, 455011.83282376, 454916.35875554,
       454772.27840976, 455327.4985259 , 454993.23387861, 455306.38933964,
       455098.59179048, 455004.74578809, 455213.80616868, 455281.03457691,
       455071.66275204, 455194.67315399, 455079.18807832, 454896.63143717,
       455028.77263415, 455150.70610067, 455216.47977772, 454642.38072271,
       455191.5635795 , 455093.77187845, 455291.60398039, 455549.18187558,
       455413.97548669, 455207.24306285, 455133.63004923, 455205.88853936,
       455331.79063704, 454642.48408079, 455303.58341779, 454763.9232156 ,
       455527.98419161, 455324.29152424, 454942.51242081, 455210.96024214,
       454672.84242371, 454996.83773392, 455221.27135257, 455538.36317757,
       455107.79721931, 455306.25896835, 454974.88324449, 454988.7556759 ,
       455077.10606245, 454830.34775778, 455112.94603503, 455257.64329253,
       454875.07155787, 455128.74212957, 454983.16241865, 454856.146752  ,
       455221.14688153, 455010.1178655 , 455177.77674022, 455219.43426975,
       454678.50111122, 455299.85381307, 454918.33368814, 455299.92829365,
       454923.3927731 , 455094.34777815, 455083.50587807, 455010.99299638,
       455045.29632053, 455359.0296432 , 455303.62674853, 455171.87021146,
       454974.97204093, 454841.10718388, 455193.88034302, 455303.12995839,
       455238.36962569, 455155.24754713, 455035.99831668, 455276.75262672,
       454979.62071224, 454911.20076895, 455071.41988421, 454953.03744156,
       455172.96056982, 454910.09175664, 454830.02251092, 455235.08411072,
       455412.73767619, 454747.39199055, 455143.32001957, 455206.04595149,
       455016.32283323, 455171.36185498, 455183.64225282, 455176.21611173,
       455252.38023863, 454801.38769276, 455202.48950186, 455395.58580968,
       455199.7903187 , 454892.71171666, 454683.44443702, 454823.2027137 ,
       454882.83607571, 455158.90446736, 454701.42947813, 455150.46989421,
       454767.77331308, 455432.18766695, 454848.26192369, 454758.70791711,
       455150.28783991, 455396.18905075, 454996.26154983, 454889.14439022,
       455062.00232724, 455080.53168125, 455025.64551661, 455366.74851703,
       455136.35592027, 455449.23274057, 454899.0994807 , 454629.97372285,
       454950.82671522, 455019.78256172, 454758.9271043 , 455324.96074648,
       454984.98740994, 454988.37525452, 455306.97845192, 455026.9892897 ,
       455230.37954039, 455234.99594488, 455199.37437193, 455500.30750903,
       454762.19461193, 454809.58405169, 455396.53580078, 454780.71059593,
       455367.03264897, 454903.45886844, 455068.29460936, 454983.5274228 ,
       455151.42266684, 454886.84171208, 455163.32412946, 455275.46445712,
       455070.3499195 , 455419.47869125, 455019.31829903, 454999.03569743,
       455040.03537354, 455143.83692387, 455099.69266047, 455163.7588945 ,
       455081.50695403, 455079.71608337, 455049.93065044, 455325.85600943,
       455094.29954486, 455223.63595412, 454910.01279345, 455175.48950042,
       455189.34843019, 455224.01187723, 454856.2869547 , 454669.70369505,
       455143.39943185, 455404.01417525, 455221.03676893, 454884.342961  ,
       455245.47667532, 455058.09964446, 455115.62633073, 455597.0034266 ,
       454725.03594621, 454960.21224893, 454828.01304437, 454883.24269229,
       454925.19449076, 454893.81462881, 455057.38211261, 455130.17493527,
       454973.49393543, 455036.08947503, 455394.54304116, 455155.63403318,
       455050.09155532, 454747.3758607 , 454800.14383043, 455380.56899265,
       455158.57250197, 455228.96562585, 455350.30408548, 455325.08769234,
       454907.98149124, 454976.20847349, 455097.36130561, 454828.56377065,
       454672.53469165, 455056.03966842, 454877.51206987, 454920.51517645,
       454788.33552178, 454951.13226086, 454762.00227613, 454936.91651749,
       455197.94601393, 454997.50323506, 454904.93037029, 455097.99410111,
       454804.67113968, 455521.15652966, 455292.56404754, 455024.55202813,
       455206.21619333, 455125.89285442, 454788.2485093 , 455390.59255827,
       455209.65377332, 455221.46238144, 454934.68753201, 455207.69869016,
       455142.09572941, 455041.87722548, 455056.75760574, 455240.12367817,
       454702.81417213, 455245.98047055, 455252.03148684, 454976.24448693,
       454931.04469162, 454966.60619685, 454939.44078039, 455218.71669356,
       455013.94260827, 455167.67031163, 454872.85337284, 455384.9842923 ,
       454808.16917088, 455047.67489842, 455124.17708545, 454762.41517121,
       455302.98000544, 454935.33741101, 455299.39246967, 454950.59269535,
       455006.19368012, 455266.07201219, 455031.78790574, 455220.14399458,
       455291.4190403 , 454795.59838689, 455344.2599083 , 455185.06670141,
       455374.78822769, 455190.86415377, 454541.74198229, 455358.98313586,
       455231.21533914, 455188.93432032, 455162.1259899 , 454899.1755936 ,
       454863.68213981, 454605.85551354, 454715.62775419, 454840.54311699,
       455487.54248184, 455151.17168967, 455380.66425192, 455207.82687681,
       454888.62603132, 454738.17456166, 455024.9784918 , 455139.94379337,
       455221.98217664, 455204.55390353, 455126.53441759, 455086.7376726 ,
       455128.8797121 , 455296.49360829, 455043.99883526, 454748.95464104,
       455060.86703652, 455104.24876049, 455286.0899198 , 455136.28167667,
       455087.53137244, 455128.64622746, 455184.33324866, 454916.88109755,
       455125.99678735, 454936.98129896, 454939.46099216, 454863.14068632,
       455196.03860174, 454764.92995524, 454851.83831246, 454863.1928641 ,
       455587.98009257, 454984.7303591 , 455063.75089519, 454819.78055703,
       454920.30929754, 455174.70148123, 455298.86286252, 455065.71457831,
       455141.63779784, 455181.26687295, 455285.21864454, 455314.56845375,
       455287.46254501, 454963.62914666, 455106.913105  , 455170.50456595,
       455006.44532283, 454922.97365648, 454903.91207306, 455276.24665504,
       454965.00334184, 455190.36783145, 455326.14005771, 454958.51142291,
       454778.52486428, 454788.71106796, 455125.53638055, 455400.37226172,
       454759.71459897, 454759.67740836, 455478.99867998, 455318.85780456,
       455272.49012207, 454884.20557228, 455315.87467506, 454998.57401693,
       455261.34864763, 455352.45458139, 454933.26124922, 454924.71380164,
       455197.30658689, 455251.93166746, 454693.46925819, 454684.98878363,
       455034.13045124, 454688.64166145, 455140.81372317, 455291.54646353,
       455084.38032155, 455119.97686296, 455220.5227315 , 454924.33772091,
       455307.43865283, 455324.59391817, 455181.87970843, 455235.61571158,
       454837.89100404, 455138.33970521, 455354.93634462, 455137.95674247,
       455294.56971706, 455364.58342954, 455136.77751807, 455272.2642869 ,
       455311.81137641, 454818.38669388, 454735.81034493, 455525.62877651,
       455230.82279524, 454944.62024761, 455192.29343211, 454681.82549476,
       454781.21115146, 454817.20293862, 455399.92634554, 455223.29970169,
       455217.86725335, 455261.2599914 , 455161.56399498, 455123.0282265 ,
       455136.15974779, 455050.54570015, 454955.27451378, 455005.61733558,
       454638.78159125, 454967.91965078, 454957.6554903 , 455283.86655585,
       455220.15968768, 454932.07655043, 454648.47256717, 455325.04064929,
       454885.13574603, 455097.80686059, 455255.63108915, 454940.92571811,
       454857.02024018, 454846.71527776, 454899.83530968, 455266.39256161,
       455077.81800047, 455056.29253828, 455260.11279599, 455271.98873024,
       455338.6212231 , 454618.74913061, 454688.98061398, 455246.08548504,
       454914.18893991, 454846.86385711, 455201.23881719, 454798.75587901,
       454743.24855531, 455191.6611427 , 454956.88071578, 455195.55516524,
       455361.12885879, 455458.16704757, 455349.07422107, 455364.76044218,
       455185.78958461, 454906.21171435, 455058.40699972, 455040.44992671,
       454557.79964014, 455513.2106333 , 454911.88916479, 455206.79355217,
       454823.77448659, 455180.37220048, 454821.96049357, 455114.03564698,
       454866.93025333, 455039.01388827, 454962.24991378, 454843.54530788,
       455082.27419361, 455494.86981819, 454775.61836432, 454883.58133551,
       455259.66863782, 455044.94164366, 455167.86459509, 454839.45377259,
       455104.91044203, 455237.94996819, 455181.47195301, 454698.22663495,
       455196.47788113, 455164.67726863, 454934.41879256, 455318.14155397,
       454963.73548382, 455067.9947901 , 454955.52897125, 455054.15328036,
       455063.76252746, 455007.47027691, 455287.05123862, 454949.35197037,
       454907.80296703, 454814.99864393, 454740.94530888, 455236.28040926,
       455113.42678463, 455122.41601482, 455335.37838124, 454948.91969239,
       454832.41636007, 455037.64456031, 455038.08215813, 454810.50884691,
       454857.68315896, 455178.33072363, 455494.99041732, 454801.71255542,
       454927.12530011, 454848.77353002, 455089.61302089, 455104.26793338,
       454893.15218837, 455079.59412223, 454501.35005043, 455206.51231299,
       455170.2379004 , 454959.8252451 , 455538.72899112, 455123.97735691,
       454603.90254788, 455389.31642465, 454944.09460599, 455105.11201115,
       455174.04013147, 455181.80321316, 454648.18466223, 455082.8462886 ,
       455012.815491  , 455131.46930576, 455033.85526285, 455161.07465113,
       454623.33410741, 455123.85024623, 455187.01881225, 455218.78757228,
       455228.55552105, 454825.89583926, 455327.70465677, 454996.70522009,
       455242.75004138, 455217.18733009, 455260.52628676, 454942.98277509,
       454868.00384075, 455362.13672518, 455174.5222612 , 454708.52751971,
       455158.59856157, 455515.19908917, 455175.27304555, 454731.83617496,
       455182.22792379, 455094.37164353, 454781.49812508, 455000.70472516,
       455087.54839439, 455327.48918206, 454970.10568865, 454969.7771564 ,
       455164.37111557, 454797.79080856, 455250.33498325, 454717.50590075,
       455176.42992546, 455220.91293377, 454720.18330393, 455477.6146513 ,
       454667.06773657, 455022.07464576, 455105.16213774, 455014.29629934,
       454709.30014335, 455054.46704836, 454947.13276013, 454990.24581914,
       454721.68814316, 455329.14158547, 455219.73264719, 455007.66313911,
       454763.47140572, 454966.89468256, 455233.40930818, 454929.28168087,
       455150.07516078, 454993.96523508, 454946.48903684, 454813.44177424,
       455169.82303548, 455155.37458549, 455030.0347714 , 455357.69536691,
       455091.93994939, 455274.14951428, 454793.24357723, 455088.93270689,
       454850.42685368, 454897.40503045, 454806.96004121, 454896.13237178,
       454909.58919474, 455200.33219424, 455043.7574459 , 455003.9003216 ,
       454896.20504547, 455084.53978209, 454808.3265914 , 454912.05035652,
       455154.26290922, 454929.51017521, 455142.98572606, 455191.2605581 ,
       455136.11443173, 455337.40667318, 454853.46611978, 455187.20800145,
       455212.21124641, 455251.63725816, 455059.92364895, 454744.32928762,
       455338.05642429, 455296.34117836, 454935.72957786, 454664.75246795,
       455547.41452038, 455304.40002438, 454939.17650127, 455285.27601699,
       455327.52776824, 454882.07449561, 454925.10827004, 455435.48317497,
       455393.09086115, 454781.33364425, 454796.50298336, 454966.98155696,
       455460.24770069, 455027.65549231, 455172.50488997, 454780.04172261,
       454922.65064827, 454795.07798892, 454962.46462541, 454918.86694282,
       454701.14003731, 454750.18872049, 455042.11613953, 455345.98860047,
       455130.59852269, 454758.53573127, 455212.10067289, 454950.10538033,
       454806.61457888, 455304.07904312, 455060.59279912, 455306.07533355,
       455107.44290696, 454757.35947124, 454798.53321179, 454943.47046817,
       454908.21267967, 455157.69729949, 454960.30205266, 455077.08098156,
       455153.75821529, 455420.2083918 , 455381.46106767, 455278.34604705,
       455427.69827212, 454861.09279824, 454861.84078406, 454851.49188949,
       454931.40132313, 455299.08210506, 455042.76981872, 454691.57116364,
       455360.22122475, 455304.7729811 , 455379.92672222, 455114.15373897,
       455084.95384821, 454923.67317807, 454990.88923813, 454892.23331677,
       454901.47381671, 455101.64338311, 454846.24053558, 455005.7421384 ,
       454749.83279938, 454917.23777903, 455096.52509142, 455079.40694348,
       455150.36025527, 454779.67688526, 454991.15363317, 454831.76976625,
       455163.69409192, 455456.72659769, 455385.68530062, 455244.49779964,
       454959.54410255, 454782.98869491, 454797.46038855, 454906.48947117,
       455096.32135716, 454736.22069853, 455101.62245657, 455251.69024429,
       455235.88217834, 455022.98733312, 455426.62471035, 455078.31100771,
       454873.07128085, 455004.38508017, 454922.02714228, 454756.027061  ,
       455267.46046251, 454826.43091899, 455042.11855788, 455423.56847906,
       455003.92077895, 455300.22389289, 455167.62018794, 454742.93344749,
       455249.38848128, 455136.39905598, 455179.4339008 , 455176.58800426,
       455149.66619597, 455065.41919622, 454995.43807215, 455257.93854834,
       455350.20502316, 455030.06100083, 454710.48893522, 454979.01696624,
       455445.21376092, 455130.26125124, 454870.79717755, 454830.60951772,
       454672.48751665, 454946.51056642, 454959.44164511, 455111.15595811,
       455313.64629886, 455110.74902291, 454962.58214144, 455005.3805247 ,
       455123.08556211, 454616.81120295, 454954.89957861, 455535.6053118 ,
       454831.14598682, 455488.7867582 , 455093.11414296, 455045.21369253,
       455243.09670867, 454884.05610292, 455256.87341045, 454954.78006198,
       455300.44258143, 455133.50878395, 455219.35382614, 454989.7905894 ,
       455166.19586522, 454840.52731712, 455481.18755427, 455156.52662314,
       455068.7887602 , 454894.14220457, 455161.4390522 , 455100.09235107,
       455112.78717043, 455504.44937166, 454659.25790226, 455468.17504138,
       454795.84444913, 455743.8104623 , 454934.52192431, 455156.3155332 ,
       455186.57697655, 454818.25913753, 455095.10628378, 455407.00920352,
       455245.14224698, 455350.99122647, 455035.05061611, 455121.99084907,
       455121.40048631, 455114.31771322, 454785.79750119, 454837.86659168,
       455144.9327126 , 454593.19336457, 455350.95043542, 455223.2938684 ,
       454667.95417657, 455290.17051126, 454686.287352  , 455239.87363223,
       454988.75192477, 455459.62018723, 455094.28413793, 455225.36875335,
       455070.8798965 , 455367.72732925, 454985.29161697, 454892.40744835,
       455470.30002071, 454702.25850206, 454945.56797281, 455066.81556313,
       455128.76393662, 454947.14973333, 455350.06195579, 454704.65383169,
       455130.96017377, 454992.95585567, 454839.1011521 , 455347.56111859,
       455105.23090153, 454706.46121345, 454901.45894429, 454942.34328709,
       455199.87223424, 455041.67668465, 454826.36202165, 454833.03250607,
       455251.29700569, 455181.63258783, 455084.21918739, 454704.98513324,
       455020.39569065, 454957.24856356, 455160.19913809, 454848.43226923,
       454675.61082802, 454861.47445797, 455238.4777049 , 455157.61559834,
       455345.73006991, 454781.22373815, 454791.09870841, 455465.69653111,
       455416.27906808, 455283.89214436, 454871.45687157, 455166.27661534,
       455494.07939841, 455669.45610468, 455305.94374615, 454950.31821399,
       454772.75229837, 455125.64253472, 455043.80099204, 454973.85246066,
       455153.43033786, 455338.71738717, 455017.36083367, 454802.26730229,
       455174.88157664, 455090.95430035, 454840.94517373, 454915.15766682,
       455221.57549853, 454991.76997541, 455030.21717811, 455177.37518084,
       455092.84280655, 454844.82702668, 455222.80379145, 454925.95334783,
       455312.26617134, 454839.1065073 , 455186.6205278 , 455090.96850098,
       455233.97788837, 454836.90647842, 455252.54495031, 455022.92691333,
       455402.83126253, 455038.66336028, 454674.6813852 , 455338.20855669,
       454756.22037854, 455027.58227638, 455608.16490166, 455043.171435  ,
       455373.70537201, 454571.41918319, 454948.76528946, 455165.55827751,
       455230.97223566, 455399.43685936, 454791.53995725, 455121.24023962])

In [60]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

In [61]:
print("MAE:", mae),
print("MSE:", mse),
print("R2 Score:", r2)

MAE: 68927.50146576142
MSE: 7248158099.883543
R2 Score: 0.003107511562617571

In [65]:
from sklearn.model_selection import KFold,cross_val_score
kf=KFold(n_splits=5,shuffle=True,random_state=42)
print(scores)

[0.77323619 0.75606228 0.74397435 0.74106368 0.73842044]

In [66]:
np.mean(scores)

np.float64(0.7505513903175421)

In [68]:
from tabulate import tabulate
results=[
    ['LinearRegression',0.7658],
    ['DecisionTreeRegressor',0.4884],
    ['RandomForestRegressor',0.7505],
    ['SVR',0.7505]
]
headers=['Algorithm','Accuracy score']
table=tabulate(results,headers=headers,tablefmt='grid',floatfmt='.2f')
print(table)

+-----------------------+------------------+
| Algorithm             |   Accuracy score |
+=======================+==================+
| LinearRegression      |             0.77 |
+-----------------------+------------------+
| DecisionTreeRegressor |             0.49 |
+-----------------------+------------------+
| RandomForestRegressor |             0.75 |
+-----------------------+------------------+
| SVR                   |             0.75 |
+-----------------------+------------------+

In [71]:
import matplotlib.pyplot as plt

In [72]:
df.head()

,age,income,experience,education,city,job_type,credit_score,loan_amount,property_value,rooms,years_in_city,house_price,employment_Full-time,employment_Part-time,employment_Self-employed
0,0.844444,0.079693,0.808511,0.666667,0.00,0.25,0.539386,0.076097,0.377343,0.400000,0.533333,388334.11,0.0,0.0,1.0
1,0.622222,0.308799,0.446809,0.000000,0.75,0.00,0.434049,0.338097,0.284933,0.495835,0.766667,455230.45,1.0,0.0,0.0
2,0.311111,0.281093,0.276596,0.666667,0.00,1.00,0.784939,0.431076,0.537068,0.400000,0.233333,473574.88,1.0,0.0,0.0
3,0.933333,0.588796,0.744681,0.666667,0.75,0.25,0.595057,0.445361,0.510251,0.000000,0.166667,548769.66,1.0,0.0,0.0
4,0.155556,0.206738,0.127660,0.000000,0.25,0.75,0.616309,0.630131,0.000000,0.800000,0.500000,257429.67,1.0,0.0,0.0